---
title: "Liner Model with Predicition"
author: "Hazel" 
date: "2025-30-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse) 
require(tigerstats)
require(knitr)

data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
```

### Model1: SIMS-ARM

```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=ARM))
```

```{r} 
basicNN + geom_point() + ggtitle("SIMS vs ARMS") + theme(plot.title = element_text(hjust=0.5, size=20))
```

### Numerical Results

```{r}
cor(SIMS~ARM,data=data)
```

### Intferential Results 

```{r}
model.1 <- 1m(SIMS~ARM,data=data)
summary.1m(model.1)
```

### Create Target 

```{r}
target <- data.frame(ARM=90, GRIP=90)
```

### Predict Target 

```{r}
predict(model.1,target,interval=c("prediction"))
```

### Model2: SIMS~GRIP

```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=GRIP))
```

```{r} 
basicNN + geom_point() + ggtitle("SIMS vs GRIP") + theme(plot.title = element_text(hjust=0.5, size=20))
```

### Numerical Results : Model2

```{r}
cor(SIMS~GRIP,data=data)
```

### Intferential Results 

```{r}
model.2 <- 2m(SIMS~GRIP,data=data)
summary.2m(model2)
```

### Predict Target Point for Model 2

```{r}
predict(model.2,target,interval=c("prediction"))
```

